### PR TITLE
Update squash qsim qemu 26stable

### PR DESCRIPTION
**Pull request by B-Bimmermann**
Dear Pranith,

this is the rebase for qemu from 2.5 to 2.6.
Every test works fine.

The main changes are:

cpus.c : 
        In qemu 2.6, qemu_start_warp_timer is set to
         QEMU_CLOCK_VIRTUAL.
vl.c   : 
        FIX inlude files for 2.6;
        FIX add all new qemu_opt* functions and use them like
         in 2.6;
        ADD add all comments and changes from 2.6
        FIX change the bootdevice like 2.6
------------------------ARM--------------------------------
op_helper.c:
        Use qemu 2.6 memory_region_get_ram_addr instead
        of the removed qemu_get_ram_ptr;
translate-a64.c :
        FIX include files;
        FIX in 2.6 MO_TE is changed to s->be_data;
        ADD add little 2.6 fixes;
helper.c:
        FIX include files;
        ADD add all new access checks from 2.6 and make
         them work with qsim;
        FIX add and change  all ARM Regs from qemu 2.6;
translate.c:
        FIX include files;
        FIX in qemu 2.6 cpu_env was changed;
        FIX in 2.6 MO_TE is changed to s->be_data;
        FIX the DO_GEN_LD/ST defines to get all 2.6 changes:
        ADD changes from qemu 2.6;
-----------------------X86--------------------------------
mem_helper.c:
        FIX Use qemu 2.6 memory_region_get_ram_addr instead
         of the removed qemu_get_ram_ptr;
        FIX In qemu 2.6 cpu->fpregs[0].mmx.q is changed to
         cpu->fpregs[0].mmx.MMX_Q(0);
seg_helper.c :
        FIX little  changes from qemu 2.6;
translate.c:
        FIX include files;
        FIX In qemu 2.6 static TCGv cpu_T[2]; is changed to
         static TCGv cpu_T0, cpu_T1 there are a lot of changes
        FIX all X86 changes from qemu 2.6 to the rebase;

I hope you have now all you need. If you need any more explanation or any other thing please commit.

Best Regards,
Benjamin

### CODE REVIEW

**Comment by pranith** [comment]
@B-Bimmermann thanks!

**Comment by B-Bimmermann** [comment]
Thank you. Would you also like to have the rebase of the xilinx qemu version ?

**Comment by pranith** [comment]
@B-Bimmermann What is the difference between Xilinx qemu and upstream qemu_v26? If the changes are something we are interested in, we can merge the xilinx version.

**Comment by B-Bimmermann** [comment]
@pranith 

The Xilinx qemu has three good patches that are not in the mainline qemu.

1. More xilinx device like the Ultrascale are support. http://www.wiki.xilinx.com/QEMU 
2.  Build a system with a Linux Overlay. This in test but works as an Example for the Ultrascale. http://www.wiki.xilinx.com/QEMU+-+Zynq+UltraScalePlus
3. The last thing is that you can run SystemC Code with a TLM interface. http://www.wiki.xilinx.com/QEMU+SystemC+and+TLM+CoSimulation

At the moment we integrate that SystemC interface to Manifold. We think we are ready with that at the end of the month.
Later we will also add the TLM SystemC interface to Manifold.

With that you can perform good test reality vs. qsim.

**Comment by pranith** [comment]
@B-Bimmermann sounds like an interesting use-case. Once you are ready with SystemC interface, let us explore integrating the Xilinx qemu too. Please keep us updated.

**Comment by B-Bimmermann** [comment]
It is late now.
I'm glad to hear from you tomorrow.

**Comment by B-Bimmermann** [comment]
I will keep you updated.

**Comment by B-Bimmermann** [comment]
Thanks for the rebase and good night.

**Comment by pranith** [comment]
@B-Bimmermann I am getting the following error with qemu v26. Did you happen to see it on your side?

$ ./qsim-fastforwarder linux/Image 4 4096 state.4.a64 a64
Opening /tmp/qsim_JpJEgL
dlsym("/tmp/qsim_JpJEgL", "qemu_init") failed:  /tmp/qsim_JpJEgL: undefined symbol: qemu_init

**Comment by B-Bimmermann** [comment]
No sorry. I will check out your qsim and your qemu this weekend and will try to reproduce this error.

**Comment by B-Bimmermann** [comment]
@pranith 
I have check the code twice and build it twice with your git version from qsim_v26.
I can't reproduce it.
Have you clean up everything?

Please take a look:
[build_log.txt](https://github.com/pranith/qemu/files/1129446/pranith_build_log.txt)
[out.txt](https://github.com/pranith/qemu/files/1129447/pranith_out.txt)

I work under:
> Linux ubuntu 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I really don't know how you get this problem. Can you try to clean your build up?

If I can help you with anything please contact me.

**Comment by pranith** [comment]
Your log contains this:

[    7.880000] smpboot: CPU0: AMD QEMU Virtual CPU version 2.5+ (fam: 06, model: 06, stepping: 03)

Looks like you are still using QEMU 2.5.

Do the following:

qsim $ cd qemu
qemu $ git checkout qsim_v26
qemu $ cd ..
qsim $ make release install
qsim $ make tests

**Comment by B-Bimmermann** [comment]
As I said in the last comment, I took care to use your GIT code and your branch V26.

Please look again for the log (now a short version):
[build_log _short.txt](https://github.com/pranith/qemu/files/1130116/pranith_build_log._short.txt)

And a new log to check up I'm on your QSIM_V26 Version:
[pranith_check.txt](https://github.com/pranith/qemu/files/1130120/pranith_check.txt)

I'm sure I used your QSIM_V26 code and I can not reproduce the error.

----------------------

> [ 7.880000] smpboot: CPU0: AMD QEMU Virtual CPU version 2.5+ (fam: 06, model: 06, stepping: 03)

I don't know why I get this massage. Have you try it with higher, lower qemu Versions ? Does this massage every time contains the right Qemu Version ?

**Comment by B-Bimmermann** [comment]
A log for your commands:
[pranith_make.txt](https://github.com/pranith/qemu/files/1130141/pranith_make.txt)

**Comment by B-Bimmermann** [comment]
@pranith  
I have test a little bit more and one time I have reproduce your Problem.

Please add in the Makefile in clean:
rm -fr lib/ include/ bin/

With this more clean build I can't reproduce it.
Have you more Problems?

We are currently working on a qemu_stable_2.8.1 / xilinx_qemu_2.8.1 merge with your qsim rebase changes. We thing in the next week we have them ready.
Are you interested in that Version?
We will use this Version to integrate SystemC.

Thanks a lot.
Benjamin

**Comment by pranith** [comment]
That didn't work for me :(. Still getting this issue on Debian 8.

For qemu 2.8, you can try rebasing on qsim_v28 branch in my qemu repository. That work is incomplete however, you have to implement state save/load since upstream removed the file descriptor based mechanism which we were using.

**Comment by B-Bimmermann** [comment]
@pranith 
I have make a rebase from the qsim_v25. But now I'm stocked.

Maybe this is a QSIM Question:
Where do you use `int qsim_loadvm_state(const char* filename)`

I have now implemented everthing von qsim_v25 and can save the state files.
But I can't load any state file. You not use "qsim_loadvm_state" in any context or I'm wrong ?

If I now get the loadvm working I can share with you a qemu2.8,xilinx2.8 (rebase qsim_v25) Version.

**Comment by pranith** [comment]
@B-Bimmermann that file descriptor based state load and save has been removed in qemu 2.8. You have to use their new mechanism. See the file migration/savevm.c for details.

**Comment by B-Bimmermann** [comment]
Dear @pranith 

I have now fixed it. But my question still exists. When and where do you use qsim_loadvm_state?
In my opinion you never use qsim_loadvm_state, you only use load_vmstate.

If you are interested in my fix please take a look. 
https://github.com/B-Bimmermann/qemu-qsim/commit/3eac83d972fa69dd02be86d4f444f8f8b89eca1f

Now I must test the ARM Code, the X86 works pretty well.
I think at the end of the week I can give you a PR if you like and every test works fine.

**Comment by pranith** [comment]
@B-Bimmermann We use qsim_loadvm_state() from qsim to load the saved state files. Grepping for it gives:

qsim.cpp:174:  Mgzd::sym(qsim_loadvm_state,    qemu_lib, "qsim_loadvm_state"   );
qsim.h:141:    int      (*qsim_loadvm_state) (const char *filename);

**Comment by pranith** [comment]
@B-Bimmermann you are right actually. It doesn't look like we are using this function. You can delete this. Thanks!

**Comment by pranith** [comment]
@B-Bimmermann were you able to make any progress on 2.8? Let me know if you are stuck and if I can help.

**Comment by B-Bimmermann** [comment]
@pranith Yes, we have made a good progress with the X86. This is so far finished and works without errors.
The ARM unfortunately generates problems with several CPUs. This is due to the merge of QEMU with XILINX-QEMU. I could reproduce the error in XILINX-QEMU without merge and opened a tiket in the XILINX-QEMU repository. I think this problem is fixed soon.
https://github.com/Xilinx/qemu/issues/25

The Rebase is from the QSIM-V25 version and is, as I said, on a merge of QEMU-28 and XILINX-QEMU. If you want I can send you all files via PL.

We are now going to install the Ultrascale in QSIM. For this, we used the arm-generic-fdt-system used by XILINX-QEMU. This would make it possible to use use all systems which are described by an fdt and which are supported by the arm-generic-fdt-system start in QSIM.

If you want to have a short overview about Xilinx-arm-generic-fdt-system please look here:
https://github.com/Xilinx/qemu/blob/master/hw/arm/arm_generic_fdt.c

The only thing you can help is if you look at the tiket and also try to fix it, but I think xilinx will work on it.

If you want to have a short overview about the code please look here:
https://github.com/B-Bimmermann/qemu-qsim/tree/qemu_main_stable-2.8_qemu_xilinx-2.8_pranith_qsim_v25_rebase_fix

Thanks for the asking and have a nice day.

**Pull request merged**
